# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


# ===================================================================
# CargoWhale specific properties
# ===================================================================

cargowhale:
  docker:
    uri: http://localhost:2375

  metrics:
    logs:
      enabled: true
      period: 60
      prefix: cargowhale
    graphite:
      enabled: false
      host: graphite
      port: 2003
      period: 60
      prefix: cargowhale
